[package]
name = "limon-server"
version = "0.1.0"
edition = "2021"

[dependencies]
utoipa-swagger-ui = { version = "2", features = ["axum"] }
hyper = "*"
serde = "*"
serde_json = "*"
tokio = { version = "1.21.2", features = ["full"] }
tokio-util = "*"
chrono = { version = "0.4", features = ["serde"] }
rsa = { version = "*", features = ["serde"] }
jsonwebtoken = "8.1"
anyhow = "*"
once_cell = "*"
tracing = "0.1"
tracing-subscriber = "0.3"
async-trait = "*"
http-body = "0.4.5"
toml = "*"
crossbeam-channel = "*"
futures = "*"
r2d2 = "*"
r2d2_sqlite = "*"
rand = "*"


[dependencies.axum]
version = "0.5"
features = ["http2", "ws", "headers"]

[dependencies.tower]
version = "0.4"
features = ["limit", "timeout", "util"]

[dependencies.utoipa]
version = "2"
features = ["axum_extras", "chrono", "decimal", "uuid"]

[dependencies.uuid]
version = "1.2.1"
features = [
    "v4",
    # "v7",
    "fast-rng",
    "macro-diagnostics",
    "serde",
]

[dependencies.diesel]
version = "2.0.0"
features = ["sqlite", "uuid", "chrono", "r2d2"]

[dev-dependencies]
reqwest = {version = "*", features = ["json"]}
lazy_static = "*"

[features]
default = ["sqlite"]
sqlite = []
mysql = []
pg = []
all = ["sqlite", "mysql", "pg"]
