[package]
name = "limit-test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
limit-deps = { path = "../limit-deps" }
limit-am = { path = "../limit-am" }
limit-server-auth = { path = "../limit-server-auth" }
limit-db = { path = "../limit-db" }
limit-config = { path = "../limit-config" }
