[package]
name = "volo-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11"
futures = "0.3"
async-trait = "0.1"

volo = "0.2"
volo-grpc = "0.2"

[build-dependencies]
volo-build = "0.2"
