name: Rust

on:
  push:
    branches: ["master", "subs"]
  pull_request:
    types:
      - review_requested
      - ready_for_review
      - opened
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          override: true
          components: rustfmt, clippy
      - name: Install diesel_cli
        run: cargo install diesel_cli --no-default-features --features sqlite
      - name: Run diesel migration
        run: diesel migration run
      - name: Install protoc
        run: sudo apt install -y protobuf-compiler
      - name: Check
        run: cargo check --workspace --all-targets --all-features
      - name: Build
        run: cargo build
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6
      - name: Run tests
        run: cargo test -- --test-threads=1
